#!/bin/sh
[ ! -f target/JsonXml-0.1-jar-with-dependencies.jar ] && mvn clean package
java -cp target/JsonXml-0.1-jar-with-dependencies.jar:lib/json-lib-2.4-jdk15.jar com.github.redexpress.jsonxml.JsonXml